---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-dog-config
data:
  default.conf: |+
    server {
      listen 8080;
      server_name  my-dog;

      location / {
        default_type text/plain;
        return 200 "My Dog Deployment";
      }

      location /json {
        default_type application/json;
        return 200 "{\"data\":\"My Dog Deployment\"}";
      }}

    server {
      listen 9080;
      server_name  my-dog;
      location /healthz {
        default_type text/plain;
        return 200 "OK";
      }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dog
  name: my-dog
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-dog
  template:
    metadata:
      labels:
        app: my-dog
    spec:
      containers:
      - name: my-dog
        image: nginx:stable
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9080
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: config
          configMap:
            name: nginx-dog-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-dog
  name: my-dog-svc
spec:
  ports:
  - name: my-dog
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-dog
  type: ClusterIP
...
